# TODO: Configure these values for your SonarCloud project
sonar.projectKey=wlan-kabel_CI-CD-MCM-Vollmann
sonar.organization=wlan-kabel

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
