apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: product-catalog
type: Opaque
stringData:
  POSTGRES_USER: catalog
  POSTGRES_PASSWORD: catalog123
  POSTGRES_DB: productcatalog
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: product-catalog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: product-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "catalog", "-d", "productcatalog"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: product-catalog
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
